imports:
  - datasets.yaml
  - uq_methods_cod.yaml

data_dir: Data/CoD/raw
model: llama3-1_8B
output_dir: results/cod/brier
results_path: results/cod/brier

runs: [0, 1, 2, 3, 4]

metrics:
  - '@baseline_methods'
  - '@cot_methods'
  - '@ap_methods'
  - '@true_probability_methods'
  - '@self_probing_methods'
