imports:
  - datasets.yaml
  - uq_methods_cot.yaml

data_dir: Data/CoT/raw
model: llama3-1_8B
output_dir: results/cot/brier
results_path: results/cot/brier

runs:
  - 0
  - 1
  - 2
  - 3
  - 4

# metric groups using @ references to imported groups
metrics:
  - '@baseline_methods'
  - '@cot_methods'
  - '@true_probability_methods'
  - '@self_probing_methods'
