# Configuration for Chain-of-Thought (CoT) metrics

# Base paths
data_path: "Data/CoT/raw"
output_path: "Data/CoT/processed"
results_path: "results"

# Model and runs
model: "llama3-1_8B"
runs: [0, 1, 2, 3, 4]

# Datasets to process
datasets:
  - "2WikimhQA"
  - "HotpotQA"
  - "GSM8K"
  - "SVAMP"
  - "ASDiv"

# Uncertainty metrics to use
uncertainty_metrics:
  - "self-probing"
  - "probas-mean"
  - "probas-min"
  - "tokensar"
  - "ptrue"

# Evaluation metrics to compute
evaluation_metrics:
  - "auroc"
  - "brier"
  - "ece"
  - "accuracy"
