imports:
  - datasets.yaml
  - uq_methods_cot.yaml

data_dir: Data/CoT/raw
model: llama3-1_8B
output_dir: results/cot/ece
results_path: results/cot/ece

runs:
  - 0
  - 1
  - 2
  - 3
  - 4

n_bins: 10

# metric groups using @ references
metrics:
  - '@baseline_methods'
  - '@cot_methods'
  - '@ap_methods'
  - '@true_probability_methods'
  - '@self_probing_methods'
